# Generated by Django 4.0 on 2023-03-07 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('translations', models.CharField(max_length=250)),
                ('example', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ('body',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('note', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='file/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_dictionary', to='core.user')),
                ('student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('word', models.ManyToManyField(to='dictionary.Word')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
                'ordering': ('title',),
            },
        ),
    ]
