# Generated by Django 4.0 on 2023-03-07 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_answers', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionary')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('correct_answers', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Учить'), ('done', 'Выучено'), ('disable', 'Отложено')], default='active', max_length=10)),
                ('all_attempts', models.IntegerField(default=0)),
                ('all_correct_answers', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='dictionary.word')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
