# Generated by Django 4.1.4 on 2022-12-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_card_correct_answers_card_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='all_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='all_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
