# Generated by Django 4.1.4 on 2022-12-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_card_all_attempts_card_all_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lesson.lesson'),
        ),
    ]
