# Generated by Django 4.1.4 on 2022-12-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_card_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='attempts',
        ),
    ]
